apiVersion: v1
kind: Pod
metadata:
  name: redis-connect-pod
spec:
  containers:
    - name: redis-connect
      image: kgks/k8s-tutorial:0.0.2

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis
spec:
  replicas: 2
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis/redis-stack
          ports:
            - containerPort: 6379
            - containerPort: 8001
  selector:
    matchLabels:
      app: redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
    - port: 8001
      targetPort: 8001
      name: redis-cli
  