apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 3
  strategy: # change here
    type: RollingUpdate
  selector:
    matchLabels:
      app: test-deployment
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      containers:
      - name: test-deployment
        image: kgks/k8s-tutorial:0.0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name:  service-test-deployment
spec:
  selector:
    app:  test-deployment
  type:  LoadBalancer
  ports:
  - port:  3000
    targetPort:  3000
