apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server-1
  labels:
    app: server-1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: server-1
    spec:
      containers:
      - name: server-1
        image: kgks/k8s-tutorial:server-1
        ports: 
        - containerPort: 3000
  selector:
    matchLabels:
      app: server-1
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server-2
  labels:
    app: server-2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: server-2
    spec:
      containers:
      - name: server-2
        image: kgks/k8s-tutorial:server-2
        ports: 
        - containerPort: 3000
  selector:
    matchLabels:
      app: server-2
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: server-3
  labels:
    app: server-3
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: server-3
    spec:
      containers:
      - name: server-3
        image: kgks/k8s-tutorial:server-3
        ports: 
        - containerPort: 3000
  selector:
    matchLabels:
      app: server-3
---
apiVersion: v1
kind: Service
metadata:
  name: server-1
spec:
  selector:
    app: server-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server-2
spec:
  selector:
    app: server-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server-3
spec:
  selector:
    app: server-3
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /server1
        pathType: Prefix
        backend:
          service:
            name: server-1
            port:
              number: 80
      - path: /server2
        pathType: Prefix
        backend:
          service:
            name: server-2
            port:
              number: 80
      - path: /server3
        pathType: Prefix
        backend:
          service:
            name: server-3
            port:
              number: 80
