apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-connect-rc
spec:
  replicas: 1
  selector: 
    app: redis-connect
  template:
    metadata:
      name: redis-connect
      labels:
        app: redis-connect
    spec:
      containers:
      - name: redis-connect
        image: kgks/k8s-tutorial:0.0.2
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis/redis-stack
        ports:
        - containerPort: 6379
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  - port: 8001
    targetPort: 8001
    nodePort: 30002
    name: redis-cli
