apiVersion: v1
kind: Pod
metadata:
  name: empty-dir
spec:
  containers:
  - name: web-server
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true

  - name: html-generator
    image: luksa/fortune
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  volumes:
  - name: html
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: empty-dir
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

